export const data = [
  {
    id: 12,
    title: "Russell Test",
    link: "/test",
    summary: "This is an example",
  },
  {
    id: 0,
    title: "Video Interview Cheat Sheet",
    link: "/antd-demo/public/helpPages/image_cy119m.png",
    summary: "Last minute interview tips.",
  },
  {
    id: 1,
    title: "How to get Network Test Results",
    link: "/antd-demo/public/helpPages/debugDiagnose.md",
    summary: "These steps will help us debug and diagnose your issue!",
  },
  {
    id: 2,
    title: "Video Interview Errors",
    link: "antd-demo/public/helpPages/videoInterviewErrors.md",
    summary: "These are common interview errors and how to fix them.",
  },
  {
    id: 3,
    title: "One Way Video Interview Instructions",
    link: "antd-demo/public/helpPages/videoInterviewInstructions.md",
    summary: "Instructions for completing a one-way video interview.",
  },
  {
    id: 4,
    title: "Camera Permissions Denied",
    link: "/cameraPermission",
    summary: "Managing camera permissions.",
  },
  {
    id: 5,
    title: "What is a One Way Video Interview?",
    link: "antd-demo/public/helpPages/oneWayInterview.md",
    summary: "What is a one-way interview?",
  },
  {
    id: 6,
    title: "Video Interview FAQ",
    link: "antd-demo/public/helpPages/videoInterviewFAQ.md",
    summary: "Commonly asked questions about our video interviews.",
  },
  {
    id: 7,
    title: "Studdering Issues on iOS or Safari",
    link: "antd-demo/public/helpPages/studderingIssues.md",
    summary: "Current fixes for studdering issues.",
  },
  {
    id: 8,
    title: "Live Interview Tips",
    link: "antd-demo/public/helpPages/liveInterviewTips.md",
    summary: "Tips for optimizing live interviews.",
  },
  {
    id: 9,
    title: "Enabling Camera Permissions with Windows",
    link: "antd-demo/public/helpPages/cameraPermissionsWindows.md",
    summary: "How to enable camera permissions for Windows OS.",
  },
  {
    id: 10,
    title: "Deephire Onboarding",
    link: "antd-demo/public/helpPages/onboarding.md",
    summary: "Onboarding resources",
  },
  {
    id: 11,
    title: "Deephire & Clockwork Integration",
    link: "antd-demo/public/helpPages/clockworkIntegration.md",
    summary: "How to integrate Deephire and Clockwork platforms.",
  },
];
